package Application;

import ApiBDD.Parameter;
import ApiBDD.ResultSetTableModel;
import ApiBDD.db_connection;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.PrintJob;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Application.MainPrincipal;

public class Recu extends javax.swing.JFrame {

    ResultSet rs;
    db_connection db;

    /**
     * Creates new form Recu
     */
    public Recu() {
        db = new db_connection(new Parameter().HOST_DB, new Parameter().USERNAME_DB, new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        initComponents();
        inporter();
        date();
    }

    /*
     ***************************************************************************************
     * Affichage tableau
     * *************************************************************************************
     */
    public void inporter() {
        String colon_cahier[] = {"num_facture", "code_produit", "reference", "prix_vente", "stock_sortie", "subtotal"};
        rs = db.fcSelectCommand(colon_cahier, "vente", "num_facture='" + MainPrincipal.txtfac.getText() + "'");
        tbleImp.setModel(new ResultSetTableModel(rs));
        lbltotal.setText(MainPrincipal.lbltot2.getText());
        lblcash.setText(MainPrincipal.txtcascahier.getText());
        payapres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelToPrint = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbleImp = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblpay = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        lblcash = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblheure = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelToPrint.setBackground(new java.awt.Color(255, 255, 255));
        panelToPrint.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("R e ç u");
        panelToPrint.add(jLabel18);
        jLabel18.setBounds(320, 20, 140, 40);

        tbleImp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "num_facture", "code_produit", "reference", "Prix de vente", "Stock sortire", "total "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbleImp.setSelectionBackground(new java.awt.Color(192, 27, 54));
        tbleImp.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tbleImp);

        panelToPrint.add(jScrollPane2);
        jScrollPane2.setBounds(20, 120, 790, 80);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Payé aprés :");
        panelToPrint.add(jLabel2);
        jLabel2.setBounds(500, 290, 120, 28);

        lblpay.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblpay.setForeground(new java.awt.Color(102, 102, 102));
        lblpay.setText("xx");
        lblpay.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        panelToPrint.add(lblpay);
        lblpay.setBounds(680, 290, 83, 28);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Cash  :");
        panelToPrint.add(jLabel5);
        jLabel5.setBounds(520, 250, 83, 28);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("total :");
        panelToPrint.add(jLabel6);
        jLabel6.setBounds(530, 210, 83, 28);

        lbltotal.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbltotal.setForeground(new java.awt.Color(102, 102, 102));
        lbltotal.setText("xx");
        panelToPrint.add(lbltotal);
        lbltotal.setBounds(690, 210, 83, 28);

        lblcash.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblcash.setForeground(new java.awt.Color(102, 102, 102));
        lblcash.setText("xx");
        panelToPrint.add(lblcash);
        lblcash.setBounds(690, 250, 83, 28);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelToPrint.add(jButton1);
        jButton1.setBounds(60, 260, 140, 40);

        lblheure.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblheure.setForeground(new java.awt.Color(102, 102, 102));
        lblheure.setText("date :");
        panelToPrint.add(lblheure);
        lblheure.setBounds(190, 90, 220, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText(" heure :");
        panelToPrint.add(jLabel4);
        jLabel4.setBounds(410, 90, 180, 17);

        lbldate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldate.setForeground(new java.awt.Color(102, 102, 102));
        lbldate.setText("date :");
        panelToPrint.add(lbldate);
        lbldate.setBounds(620, 90, 190, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("date :");
        panelToPrint.add(jLabel8);
        jLabel8.setBounds(30, 90, 150, 17);

        jLabel49.setBackground(new java.awt.Color(192, 27, 54));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setOpaque(true);
        panelToPrint.add(jLabel49);
        jLabel49.setBounds(290, 0, 200, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelToPrint, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelToPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     ***************************************************************************************
     * Retour amin'ilay fenêtre mainPrincipal
     * *************************************************************************************
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //cachier s = new cachier();
        MainPrincipal s = new MainPrincipal();
        s.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
     ***************************************************************************************
     * Date
     * *************************************************************************************
     */
    public void date() {

        lbldate.setText(MainPrincipal.lbl1.getText());
        lblheure.setText(MainPrincipal.lbl2.getText());
    }

    /*
     ***************************************************************************************
     * Pay après
     * *************************************************************************************
     */
    public void payapres() {
        int a = Integer.parseInt(MainPrincipal.lbltot2.getText());
        int b = Integer.parseInt(MainPrincipal.txtcascahier.getText());
        int c = b - a;
        lblpay.setText(Integer.toString(c));
    }

    /*
     ***************************************************************************************
     * Non modifiable
     * *************************************************************************************
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblcash;
    public javax.swing.JLabel lbldate;
    public javax.swing.JLabel lblheure;
    public javax.swing.JLabel lblpay;
    public javax.swing.JLabel lbltotal;
    public javax.swing.JPanel panelToPrint;
    public javax.swing.JTable tbleImp;
    // End of variables declaration//GEN-END:variables


    /*
     ***************************************************************************************
     * Imprimer fa tsy mbola mandeha
     * *************************************************************************************
     */
    private void printRecord(final JPanel panel) {
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("Print Recorder");
        printerJob.setPrintable(new Printable() {

            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D graphics2D = (Graphics2D) graphics;
                graphics2D.translate(pageFormat.getImageableX() * 2, pageFormat.getImageableY() * 2);
                graphics2D.scale(0.5, 0.5);

                panel.paint(graphics2D);
                return Printable.PAGE_EXISTS;
            }
        });
        boolean returningResult = printerJob.printDialog();
        // check if dilog is showing
        if (returningResult) {
            try {
                printerJob.print();
            } catch (PrinterException printerException) {
                JOptionPane.showMessageDialog(this, "Print Error: " + printerException.getMessage());
            }
        }
    }

}
